package com.hexis.bi.utils.constants

internal object TerraProviders {
    const val HEALTH_CONNECT = "HEALTH_CONNECT"
    const val DUMMY = "DUMMY"

    // Wearables
    const val OURA = "OURA"
    const val WHOOP = "WHOOP"
    const val FITBIT = "FITBIT"
    const val GARMIN = "GARMIN"
    const val POLAR = "POLAR"
    const val COROS = "COROS"
    const val SUUNTO = "SUUNTO"
    const val WITHINGS = "WITHINGS"
    const val ZEPP = "ZEPP"
    const val BIOSTRAP = "BIOSTRAP"
    const val HEALTHGAUGE = "HEALTHGAUGE"
    const val INBODY = "INBODY"
    const val SOMNOFY = "SOMNOFY"
    const val CORE = "CORE"
    const val MOXY = "MOXY"
    const val PUL = "PUL"
    const val OMRON = "OMRON"
    const val CARDIOMOOD = "CARDIOMOOD"

    // Other apps
    const val GOOGLE = "GOOGLE"
    const val PELOTON = "PELOTON"
    const val WAHOO = "WAHOO"
    const val HAMMERHEAD = "HAMMERHEAD"
    const val XOSS = "XOSS"
    const val BRYTONSPORT = "BRYTONSPORT"
    const val LEZYNE = "LEZYNE"
    const val TECHNOGYM = "TECHNOGYM"
    const val CONCEPT2 = "CONCEPT2"
    const val DECATHLON = "DECATHLON"
    const val CATAPULTONE = "CATAPULTONE"
    const val TRIDOT = "TRIDOT"
    const val ULTRAHUMAN = "ULTRAHUMAN"
    const val TRAININGPEAKS = "TRAININGPEAKS"
    const val TRAINERROAD = "TRAINERROAD"
    const val FINALSURGE = "FINALSURGE"
    const val ELITEHRV = "ELITEHRV"
    const val HEVY = "HEVY"
    const val TRAINXHALE = "TRAINXHALE"
    const val TRAINASONE = "TRAINASONE"
    const val ROUVY = "ROUVY"
    const val ZWIFT = "ZWIFT"
    const val RIDEWITHGPS = "RIDEWITHGPS"
    const val MAPMYTRACKS = "MAPMYTRACKS"
    const val MAPMYFITNESS = "MAPMYFITNESS"
    const val KOMOOT = "KOMOOT"
    const val CYCLINGANALYTICS = "CYCLINGANALYTICS"
    const val VELOHERO = "VELOHERO"
    const val XERT = "XERT"
    const val TREDICT = "TREDICT"
    const val UNDERARMOUR = "UNDERARMOUR"
    const val CLUE = "CLUE"
    const val FLO = "FLO"
    const val WGER = "WGER"
    const val NUTRACHECK = "NUTRACHECK"
    const val MACROSFIRST = "MACROSFIRST"
    const val MYMACROSPLUS = "MYMACROSPLUS"
    const val MYFITNESSPAL = "MYFITNESSPAL"
    const val CRONOMETER = "CRONOMETER"
    const val FATSECRET = "FATSECRET"
    const val EATTHISMUCH = "EATTHISMUCH"
    const val KETOMOJOEU = "KETOMOJOEU"
    const val KETOMOJOUS = "KETOMOJOUS"
    const val BODITRAX = "BODITRAX"
}

internal object TerraCacheConstants {
    const val RANGE_CACHE_TTL_MS = 60_000L
}

internal object HealthConnectConstants {
    const val PACKAGE_NAME = "com.google.android.apps.healthdata"
    const val MARKET_URI = "market://details?id=$PACKAGE_NAME"
    const val PLAY_STORE_URI = "https://play.google.com/store/apps/details?id=$PACKAGE_NAME"
}
