package com.hexis.bi.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

/** Tokens not on [androidx.compose.material3.ColorScheme]; read via [NocturnePulseTheme.extendedColors]. */
@Immutable
data class ExtendedColors(
    val positive: Color,
    val negative: Color,
    val chartArea: Color,
    val chartLine: Color,
    val chartCenterLine: Color,
    val chartGridLine: Color,
    val chartVerticalLine: Color,
    val chartAxisLine: Color,
    val chartBoundaryLine: Color,
    val chartLeanAdvantage: Color,
    val chartFatAdvantage: Color,
    val chartZeroLabel: Color,
    val chartSelectionLine: Color,
    val bodyMesh: Color,
    val accentBright: Color,
    val accentDeep: Color,
    val accentContainer: Color,
    val cardBorder: Color,
    val tileSurface: Color,
    val textTertiary: Color,
    val timestamp: Color,
    val screenMeshTop: Color,
    val screenMeshBottom: Color,
    val glassCardFillTop: Color,
    val glassCardFillBottom: Color,
    val glassCardHighlightTopStart: Color,
    val glassCardHighlightBottomEnd: Color,
    val surfaceTranslucent: Color,
    val destructive: Color,
    val accentBlue: Color,
    val gaugeLow: Color,
    val gaugeMid: Color,
    val gaugeHigh: Color,
    val gaugeTrack: Color,
    // Blue accents (legacy filled-button gradient)
    val blue200: Color,
    val blue300: Color,
    // Neutral grays
    val gray200: Color,
    val gray300: Color,
    // Scan visuals
    val scannerShadowStart: Color,
    val scannerShadowEnd: Color,
    val scanLoaderTrack: Color,
    val scanSparklineMarkerFill: Color,
    // Reds / status
    val red100: Color,
    val red300: Color,
    val green: Color,
    val yellow: Color,
    // Sleep stages
    val sleepStageAwake: Color,
    val sleepStageRem: Color,
    val sleepStageDeep: Color,
    val sleepStageLight: Color,
    // Body comparison toggle
    val bodyToggleTrackBorder: Color,
    val bodyToggleSelectedChipFill: Color,
    val bodyToggleSelectedLabel: Color,
    val bodyToggleUnselectedLabel: Color,
    // Primary (gradient) button
    val primaryButtonGradientTop: Color,
    val primaryButtonGradientBottom: Color,
    val primaryButtonDisabledFill: Color,
    // Glass surfaces
    val glassTrackFill: Color,
    val glassSelectionFill: Color,
    val glassRimHighlight: Color,
    // Chart tooltip
    val chartTooltipFill: Color,
    val chartTooltipBorder: Color,
    // Activity charts
    val activityProgressTrack: Color,
    val activityStepsProgress: Color,
    val activityDistanceProgress: Color,
    val activityIdleBar: Color,
    val activityVerticalGridLine: Color,
    // Slider
    val sliderLabel: Color,
    val sliderActiveTrack: Color,
    val sliderInactiveTrack: Color,
    // Gradient divider
    val gradientDividerEdge: Color,
    val gradientDividerCenter: Color,
    // Step indicator / progress track
    val stepIndicatorTrack: Color,
    // Switch
    val switchActiveTrackTop: Color,
    val switchActiveTrackBottom: Color,
    val switchThumbShadow: Color,
    // Extra chart lines
    val chartHrvLine: Color,
    val chartGridLineHorizontal: Color,
    val chartGridLineVertical: Color,
)

internal val DefaultExtendedColors = ExtendedColors(
    positive = Positive,
    negative = Negative,
    chartArea = ChartBlue,
    chartLine = ChartTeal,
    chartCenterLine = ChartCenterLine,
    chartGridLine = ChartGridLine,
    chartVerticalLine = ChartVerticalLine,
    chartAxisLine = ChartAxisLine,
    chartBoundaryLine = ChartBoundaryLine,
    chartLeanAdvantage = ChartLeanAdvantage,
    chartFatAdvantage = ChartFatAdvantage,
    chartZeroLabel = ChartZeroLabel,
    chartSelectionLine = ChartSelectionLine,
    bodyMesh = BodyCyan,
    accentBright = Green400,
    accentDeep = GreenDeep,
    accentContainer = GreenSoft,
    cardBorder = Hairline,
    tileSurface = SurfaceMuted,
    textTertiary = TextTertiary,
    timestamp = TextMuted,
    screenMeshTop = MeshTop,
    screenMeshBottom = MeshBottom,
    glassCardFillTop = BodyGlassGreen,
    glassCardFillBottom = BodyGlassInk,
    glassCardHighlightTopStart = BodyGlassHighlightTopStart,
    glassCardHighlightBottomEnd = BodyGlassHighlightBottomEnd,
    surfaceTranslucent = SurfaceTranslucent,
    destructive = ActionRed,
    accentBlue = AccentBlue,
    gaugeLow = GaugeLow,
    gaugeMid = GaugeMid,
    gaugeHigh = GaugeHigh,
    gaugeTrack = GaugeTrack,
    blue200 = Blue200,
    blue300 = Blue300,
    gray200 = Gray200,
    gray300 = Gray300,
    scannerShadowStart = ScannerShadowStart,
    scannerShadowEnd = ScannerShadowEnd,
    scanLoaderTrack = ScanLoaderTrack,
    scanSparklineMarkerFill = ScanSparklineMarkerFill,
    red100 = Red100,
    red300 = Red300,
    green = Green,
    yellow = Yellow,
    sleepStageAwake = SleepStageAwake,
    sleepStageRem = SleepStageRem,
    sleepStageDeep = SleepStageDeep,
    sleepStageLight = SleepStageLight,
    bodyToggleTrackBorder = BodyToggleTrackBorder,
    bodyToggleSelectedChipFill = BodyToggleSelectedChipFill,
    bodyToggleSelectedLabel = BodyToggleSelectedLabel,
    bodyToggleUnselectedLabel = BodyToggleUnselectedLabel,
    primaryButtonGradientTop = PrimaryButtonGradientTop,
    primaryButtonGradientBottom = PrimaryButtonGradientBottom,
    primaryButtonDisabledFill = PrimaryButtonDisabledFill,
    glassTrackFill = GlassTrackFill,
    glassSelectionFill = GlassSelectionFill,
    glassRimHighlight = GlassRimHighlight,
    chartTooltipFill = ChartTooltipFill,
    chartTooltipBorder = ChartTooltipBorder,
    activityProgressTrack = ActivityProgressTrack,
    activityStepsProgress = ActivityStepsProgress,
    activityDistanceProgress = ActivityDistanceProgress,
    activityIdleBar = ActivityIdleBar,
    activityVerticalGridLine = ActivityVerticalGridLine,
    sliderLabel = SliderLabel,
    sliderActiveTrack = SliderActiveTrack,
    sliderInactiveTrack = SliderInactiveTrack,
    gradientDividerEdge = GradientDividerEdge,
    gradientDividerCenter = GradientDividerCenter,
    stepIndicatorTrack = StepIndicatorTrack,
    switchActiveTrackTop = SwitchActiveTrackTop,
    switchActiveTrackBottom = SwitchActiveTrackBottom,
    switchThumbShadow = SwitchThumbShadow,
    chartHrvLine = ChartHrvLine,
    chartGridLineHorizontal = ChartGridLineHorizontal,
    chartGridLineVertical = ChartGridLineVertical,
)

internal val LocalExtendedColors = staticCompositionLocalOf { DefaultExtendedColors }
